#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
replicaCount: 1

image:
  repository: postfacto/postfacto
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  create: true
  name:

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

postfacto:
  ## Default administrative user for Postfacto
  admin:
    username:
    password:
     
  ## Connection details for an external PostgreSQL database, used when bringing your
  ## own Postgres instance.
  ##
  postgresql:
    ## The host to connect to.
    ##
    host:
    ## The port to connect to.
    ##
    port: 5432
    ## The name of the database to use.
    ##
    database: postfacto
 
  ## By default Postfacto redirects to HTTPS by default, setting this to true disables 
  ## that behaviour and can be useful when getting started
  ## 
  disableSSLRedirect:
  ## The Google oAuth client ID to use to allow users to log in using a google account
  ##
  googleOAuthClientId:
 
  ## Used for signing and encryption, should be set to a random value. Required to 
  ## perserve sessions across upgrades
  ##
  secretKeyBase:

postgresql:
  ## Use the PostgreSQL chart dependency.
  ##
  ## Set to false if bringing your own PostgreSQL, and set the corresponding `secrets`
  ## fields that correspond to the PostgreSQL variables that Postfacto should use
  ## to connect to.
  ##
  ## Should be set to false if using the chart as a worker only deployment.
  ##
  enabled: true

redis:
  ## Use the Redis chart dependency.
  ##
  ## Set to false if bringing your own Redis, and set the corresponding `secrets`
  ## fields that correspond to the Redis variables that Postfacto should use
  ## to connect to.
  ##
  ## Should be set to false if using the chart as a worker only deployment.
  ##
  enabled: true

  cluster:
    enabled: false

admin-console:
  ## Use the KOTS admin console chart dependency.
  ##
  ## Set to false if not deploying with Replicated KOTS, otherwise set to true
  ##
  enabled: true

tolerations: []

affinity: {}
